#!/usr/bin/env groovy

pipeline {
    agent any
    options {
        ansiColor('xterm')
        timestamps()
    }
    stages {
       stage('Maven Clean') {
            steps {
                echo 'Building Maven...'
                sh 'mvn clean package'
            }
        }
        stage('Docker Build') {
            steps {
                echo 'Building Container...'
                script {
                    buildApp{
                        app = 'cardid'
                    }
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Run end-to-end tests...'
                build job: 'run-end-to-end-tests',
                  parameters:[
                    string(name: 'MODULE_NAME', value: 'cardid'),
                    string(name: 'MODULE_TAG', value: "${env.REQ_COMMIT_ID}-${env.BUILD_NUMBER}"),
                    booleanParam(name: 'RUN_ZAP_TESTS', value: true),
                    booleanParam(name: 'RUN_TESTS', value: true)]
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
            }
        }
    }
}
