name: Github Actions Tests

on:
  workflow_call:
    secrets:
      pact_broker_username:
        required: true
      pact_broker_password:
        required: true

permissions:
  contents: read

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      - name: Detect secrets
        uses: alphagov/pay-ci/actions/detect-secrets@master

  integration-tests:
    name: "Integration tests"
    uses: alphagov/pay-ci/.github/workflows/_run-java-tests-and-publish-pacts.yml@master
    with:
      java_version: 21

  provider-contract-tests:
    needs: integration-tests
    name: "App as provider tests"
    uses: alphagov/pay-ci/.github/workflows/_run-app-as-provider-contract-tests.yml@master
    with:
      java_version: 21
    secrets:
      pact_broker_username: ${{ secrets.pact_broker_username }}
      pact_broker_password: ${{ secrets.pact_broker_password }}

  check-docker-base-images-are-manifests:
    uses: alphagov/pay-ci/.github/workflows/_validate_docker_image_is_manifest.yml@master

