name: Trigger release

on:
  workflow_dispatch:

jobs:
  authorised_user_check:
    runs-on: ubuntu-latest
    if: github.actor == 'alphagov-pay-ci-concourse'
    steps:
      - run: echo "alphagov-pay-ci-concourse triggered a new release"

  trigger_release:
    needs: authorised_user_check
    uses: ./.github/workflows/post-merge.yml
